Add query shard tx state
ontio/ontology pull request #1033
Opened 2019-07-17 12:58 UTC by lucas7788

#issue https://github.com/ontio/ontology/issues/1028

2019-07-17 12:59 UTC, lucas7788 commented
fix issue #1028

2019-07-18 03:38 UTC, qiluge commented on core/store/ledgerstore/ledger_store.go
> +	return xshardDB.GetXShardState(crossShardTxID)
you can fetch txState from state store straightly, no need to generate xshardDB object.

2019-07-18 08:52 UTC, qiluge requested changes

2019-07-18 08:52 UTC, qiluge commented on cmd/info_cmd.go
> +			Name:        "shardtxstate",
txstate

2019-07-18 08:52 UTC, qiluge commented on cmd/info_cmd.go
> +			Usage:       "Display transaction state",
display tx state if tx invoke remote shard, or tx is shard tx

2019-07-18 09:17 UTC, qiluge commented on cmd/info_cmd.go
> +			ArgsUsage:   "<txhash> <[notifyid]>",
<txhash, [notifyId]>

2019-07-18 11:24 UTC, qiluge requested changes

2019-07-18 11:24 UTC, qiluge commented on cmd/info_cmd.go
> +		PrintInfoMsg("Cannot get SmartContractEvent by TxHash:%s.", txHash)
Cannot get txState by...

2019-07-18 11:24 UTC, qiluge commented on core/store/ledgerstore/ledger_store.go
> +func (this *LedgerStoreImp) GetShardTxState(txHash common.Uint256, notifyId uint32, isHasNotifyId bool) (*xshard_state.TxState, error) {
isHasNotifyId -> hasNotify or hasNotifyId

2019-07-18 11:24 UTC, qiluge commented on http/base/common/common.go
> +		lockedAddress = append(lockedAddress, addr.ToBase58())
addr.ToBase58() -> addr.ToHex(), because lockedAddress is contract address, use hex string is our habit.

2019-07-18 11:24 UTC, qiluge commented on http/base/rest/interfaces.go
> +		nid, nok = notifyId.(uint32)
maybe string type

2019-07-18 11:24 UTC, qiluge commented on http/base/rpc/interfaces.go
> +	switch params[0].(type) {
maybe change to str, ok := params[0].(string) ?

2019-07-18 11:24 UTC, qiluge commented on http/base/rpc/interfaces.go
> +		switch str := params[1].(type) {
also at here

2019-07-18 11:39 UTC, qiluge approved these changes

2019-07-18 15:47 UTC, merged