Gas Round Tune
ontio/ontology pull request #1144
Opened 2020-01-02 07:57 UTC by carltraveler

2020-01-03 02:52 UTC, laizy requested changes

2020-01-03 02:52 UTC, laizy commented on common/config/config.go
> +	NETWORK_ID_POLARIS_NET: constants.OPCODE_HEIGHT_UPDATE_FIRST_POLARIS, //Network polaris
`GAS_ROUND_TUNE_HEIGHT_MAINNET `

2020-02-18 05:49 UTC, Honglei-Cong commented
Could you elaborate why need to do gas tune in PR description?

2020-02-26 06:02 UTC, Honglei-Cong approved these changes

2020-02-26 07:16 UTC, laizy commented
replaced by #1161

2020-02-26 07:16 UTC, closed without merging