fix code and doc not match
ontio/ontology pull request #115
Opened 2018-05-07 08:41 UTC by xizho10

2018-05-07 09:01 UTC, Arbio5zt requested changes

2018-05-07 09:01 UTC, luodanwg commented on docs/specifications/websocketapi.md
> +## websocket api list
websocket -> Websocket

2018-05-07 11:35 UTC, laizy submitted a review, later dismissed

2018-05-08 04:20 UTC, laizy approved these changes

2018-05-08 04:21 UTC, merged