add ontfs native contract
ontio/ontology pull request #1177
Opened 2020-04-20 07:08 UTC by qingche123

* Add ontfs native contract

* Add multi files error return support.

* Add snarkPdp support

* Export CheckPdpProve for ontfs.

* Minimal changes.

* Update Makefile to enable cgo.

* Fix fileInfoList Deserialization function.

* Update AddErrorsEvent function.

* Add debug info.

* Add FirstPdp param with StoreFile.

* Disable FsSetGlobalParam interface.

* Update vk to adapt 4k.

* Add Challenge&Response function.

* DeleteFile when the last fileProve.

* Add GetChallenge&Judge function.

* Update Challenge/Response process code.

* Update FsJudge function.

* Move FsResponse and FsGetChallengeList function to node_business.go

* Fix build error.

* Update FsChallenge function and fix CleanFlag bug.

* Update FsChallenge function.

* Update clean fileinfo process code

* Fix FsGetChallengeList issue about checkWitness.

* Fix FsResponse deserialization issue.

* Add FsGetFileChallengeList function.

* Added judgment with challenge when the state is Judged.

* Challenge will report error when initiator is not the file owner.

* Fix the issue that pdp info is deleted and then added when all nodes submit last pdp.

* Allow readPledge settle when file has been deleted.

* File store time must be longer than 4hours.

Signed-off-by: Guo XiaoJie <guoxiaojie@onchain.com>

2020-04-22 08:36 UTC, laizy commented on smartcontract/service/native/ontfs/passport.go
> +		return passport.WalletAddr, fmt.Errorf("CheckPassport Verify error: %s", err.Error())
calling `err.Error` will cause panic here,  since err is nil.

2020-04-22 08:36 UTC, laizy commented on smartcontract/service/native/ontfs/result_info.go
> +	retInfo.Deserialization(source)
handle error

2020-04-22 08:36 UTC, laizy commented on smartcontract/service/native/ontfs/app_sdk.go
> +			fmt.Errorf("[APP SDK] FsGetNodeInfoList getNodeInfo(%v) error", addr)
error created and not used. do you mean `log.Errorf`?

2020-04-23 10:18 UTC, laizy commented on smartcontract/service/native/ontfs/node_info.go
> +		item, err := utils.GetStorageItem(native, iter.Key())
you can use iter.Value() directly. and call `GetValueFromRawStorageItem`

2020-04-23 10:18 UTC, laizy commented on smartcontract/service/native/ontfs/node_govern.go
> +	newNodeInfo.RestVol = oldNodeInfo.RestVol + newNodeInfo.Volume - oldNodeInfo.Volume
use ` newNodeInfo.Volume - (oldNodeInfo.Volume - oldNodeInfo.RestVol)` to avoid overflow?

2020-04-23 10:18 UTC, laizy commented on smartcontract/service/native/ontfs/node_govern.go
> +func FsNodeWithDrawProfit(native *native.NativeService) ([]byte, error) {
change `WithDraw` to `Withdraw`?

2020-04-23 10:18 UTC, laizy commented on smartcontract/service/native/ontfs/app_sdk.go
> +		r := rand.New(rand.NewSource(time.Now().Unix()))
nondeterministic execution can easily shutdown the whole network. you can use the current block hash to generate random number.

2020-04-23 10:18 UTC, laizy commented on smartcontract/service/native/ontfs/app_sdk.go
> +		count--
check `count != 0` before entering for loop to avoid underflow?

2020-04-23 10:18 UTC, laizy commented on smartcontract/service/native/ontfs/app_sdk.go
> +		if count <= 0 {
`count` is uint64, maybe use `==` to make it more clear.

2020-05-06 06:56 UTC, laizy commented on smartcontract/service/native/ontfs/file_pdp_record.go
> +func getPdpRecordMap(native *native.NativeService, fileHash []byte, fileOwner common.Address) map[common.Address]*PdpRecord {
clean unused function.

2020-05-06 06:56 UTC, laizy commented on smartcontract/service/native/ontfs/app_sdk.go
> +			pdpRecord.SettleFlag = true
seems `pdpRecord.SettleFlag` is set but not used, need update it to db?

2020-05-06 06:56 UTC, laizy commented on smartcontract/service/native/ontfs/init.go
> +	if err := globalParam.Deserialization(infoSource); err != nil {
need check witness, or clean this unused code.

2020-05-06 06:56 UTC, laizy commented on smartcontract/service/native/ontfs/node_business.go
> +	blockHeader, err := native.Store.GetHeaderByHeight(uint32(pdpData.ChallengeHeight))
call `GetBlockHash` instead.

2020-05-07 05:19 UTC, laizy commented on smartcontract/service/native/ontfs/pdp/pdp.go
> +			blockId := blocksId[chl*merkle_pdp.MerkleRootLen : (chl+1)*merkle_pdp.MerkleRootLen]
missing `blocksId` length check.

2020-05-07 05:19 UTC, laizy commented on smartcontract/service/native/ontfs/pdp/merkle_pdp/merkle_pdp.go
> +	root := proof[len(proof)-1]
may cause out of bound panic.

2020-05-07 05:19 UTC, laizy commented on smartcontract/service/native/ontfs/pdp/merkle_pdp/merkle_pdp.go
> +	res := [][]byte{data[c*32 : (c+1)*32]}
may cause out of bound access.

2020-05-07 05:19 UTC, laizy commented on smartcontract/service/native/ontfs/pdp/merkle_pdp/merkle_pdp.go
> +		copy(data, block[0:64])
why only use the first 64byte?

2020-05-07 11:19 UTC, laizy commented on smartcontract/service/native/ontfs/pdp/pdp.go
> +			challenge[i] = bigTmp.Mod(bigTmp, blockNum).Uint64()
remove duplicated challenge number?

2020-05-07 11:19 UTC, laizy commented on smartcontract/service/native/ontfs/app_sdk.go
> +		totalAddMaxBlockNumToRead += readPlan.MaxReadBlockNum
overflow check

2020-05-07 11:19 UTC, laizy commented on smartcontract/service/native/ontfs/app_sdk.go
> +	readPledge.RestMoney += newPledgeFee
make sure all operations have overflow check

2020-05-13 02:25 UTC, qingche123 commented on smartcontract/service/native/ontfs/pdp/pdp.go
> +			challenge[i] = bigTmp.Mod(bigTmp, blockNum).Uint64()
“vAdded” changes every time in the loop.  So challenge number is changing

2020-05-15 02:26 UTC, laizy commented on smartcontract/service/native/ontfs/pdp/pdp.go
> +			challenge[i] = bigTmp.Mod(bigTmp, blockNum).Uint64()
you are using `mod` operation, `a != b` , but `a % blockNum == b % blockNum` can be true.

2020-05-15 06:58 UTC, laizy requested changes

2020-05-15 06:58 UTC, laizy commented on smartcontract/service/native/ontfs/pdp/pdp.go
> +	proofPrefix := proof[0:VersionLength]
the length of `proof` is still not checked.

2020-05-15 11:43 UTC, laizy commented on smartcontract/service/native/ontfs/pdp/pdp.go
> +			if uint64(len(challenge)) >= challengeNum {
will cause dead loop if `challengeNum > blockNum`

2020-05-15 12:46 UTC, laizy approved these changes

2020-05-15 12:47 UTC, merged