change unbound and fee split
ontio/ontology pull request #1223
Opened 2020-06-04 08:47 UTC by siovanus

1. change ong unbound
2. update fee split in governance

2020-06-10 08:04 UTC, laizy requested changes

2020-06-10 08:04 UTC, laizy commented on common/config/config.go
> +	if constants.NEW_UNBOUND_GENERATION_AMOUNT[numInterval-1] != 3 ||
do you understand why the original code use `!= 1` ?

2020-06-10 08:04 UTC, laizy commented on common/constants/constants.go
>  var UNBOUND_DEADLINE = (func() uint32 {
clean this.

2020-06-10 08:04 UTC, laizy commented on smartcontract/service/native/utils/unbind_ong.go
> +		endOffset = config.GetChangeUnboundTimestamp() - constants.GENESIS_BLOCK_TIMESTAMP
clean those code , and define `config.GetChangeUnboundTimestamp() - constants.GENESIS_BLOCK_TIMESTAMP` as `GetOntHolderUnboundDeadline()` in config.go, and replace the following `constants.UNBOUND_DEADLINE`

2020-06-10 08:04 UTC, laizy commented on smartcontract/service/native/utils/unbind_ong_test.go
> +	assert.NotEqual(t, CalcUnbindOng(1, 0, TIME_INTERVAL*18),
just changing this to **not equal** makes those useless. please add ONG_TOTAL_SUPPLY testcase to avoid bugs.

2020-06-10 08:04 UTC, laizy commented on smartcontract/service/native/utils/unbind_ong_test.go
> +		config.GetChangeUnboundTimestamp()-constants.GENESIS_BLOCK_TIMESTAMP+2), uint64(2*constants.ONT_TOTAL_SUPPLY))
ditto, replace all with `GetOntHolderUnboundDeadline`

2020-06-10 10:43 UTC, laizy commented on common/config/config.go
> +func GetNewUnboundDeadline() (uint32, uint64) {
rename to `GetGovUnboundDeadline`

2020-06-10 10:43 UTC, laizy commented on smartcontract/service/native/ont/ont.go
> +		if native.Time <= config.GetOntHolderUnboundDeadline() + constants.GENESIS_BLOCK_TIMESTAMP {
use `endOffset <= config.GetOntHolderUnboundDeadline()`?

2020-06-11 03:49 UTC, siovanus commented on smartcontract/service/native/ont/ont.go
> +		if native.Time <= config.GetOntHolderUnboundDeadline() + constants.GENESIS_BLOCK_TIMESTAMP {
Done

2020-06-12 06:15 UTC, laizy commented on smartcontract/service/native/ont/ont.go
> +	return nil, UnboundOngToGovernance(native)
return BYTE_TRUE?

2020-06-12 06:15 UTC, laizy commented on smartcontract/service/native/ont/ont.go
> +	return nil, unboundOngToGovernance(native)
return `BYTE_TRUE`? since it is common practice for native contract method.

2020-06-16 12:01 UTC, laizy approved these changes

2020-06-16 12:02 UTC, merged