support bloom filter
ontio/ontology pull request #1407
Opened 2022-05-09 01:58 UTC by hero5512

2022-05-16 03:48 UTC, laizy commented on common/config/config.go
> +func GetAddFilterHeight() uint32 {
why need hardfork? this feature do not have any consensus changes.

2022-05-16 03:48 UTC, laizy commented on core/ledger/ledger.go
> +	// must init indexer before ledger store
more detail why need initialize first.

2022-05-16 03:48 UTC, laizy commented on core/store/indexstore/bloombits.go
> +		bloomData[i] = &KV{Key: bloomBitsKey(uint(i), b.section, b.head), Value: value}
reuse bloomBitsKey generated above?

2022-05-16 03:48 UTC, laizy commented on core/store/indexstore/bloombits.go
> +	key := append(append(bloomBitsPrefix, make([]byte, 10)...), hash.Bytes()...)
why 10?

2022-05-16 03:48 UTC, laizy commented on core/store/indexstore/bloombits.go
> +	// the initial height is 1 but it on ethereum is 0. so subtract 1
where substract 1?

2022-05-16 03:48 UTC, laizy commented on core/store/indexstore/indexer.go
> +	*bloomData = append(*bloomData, &KV{Key: []byte("count"), Value: data[:]})
extract out this keys as constants

2022-05-16 09:12 UTC, laizy commented on core/store/indexstore/indexer.go
> +	data, _ := i.backend.store.Get([]byte("count"))
所有对db的读写都需要包装在backend的对外函数里，类似ReadBloomBits。不要绕过直接读写背后的store。

2022-05-16 09:12 UTC, laizy commented on core/store/indexstore/indexer.go
> +	*bloomData = append(*bloomData, &KV{Key: append([]byte("shead"), data[:]...), Value: hash.Bytes()})
where bloomData used?

2022-05-16 09:12 UTC, laizy commented on core/store/indexstore/indexer.go
> +	var data [8]byte
why 8?

2022-05-16 09:12 UTC, laizy commented on core/store/indexstore/indexer.go
> +func (i *Indexer) sectionHead(section uint32) common.Hash {
what is section head used for?

2022-05-16 09:12 UTC, laizy commented on core/store/indexstore/indexer.go
> +			i.updateBlock()
why need this call?

2022-05-16 09:12 UTC, laizy commented on core/store/indexstore/bloombits.go
> +	head    common.Hash                // Head is the hash of the last header processed
why need this head field?

2022-05-16 09:12 UTC, laizy commented on core/store/ledgerstore/ledger_store.go
> +	}
这里搞复杂了呀，内存里保存一份bloombits，每生成一个区块就把bloom添加进去，到了4096个就落账。不需要做成异步的，开一堆go routine，还没有任何错误处理。

2022-05-17 02:04 UTC, laizy commented on http/ethrpc/filters/filter_system.go
> +	rmLogsChanSize = 10
```suggestion
```

2022-05-17 02:04 UTC, laizy commented on http/ethrpc/filters/filter_system.go
> +
```suggestion
```

2022-05-17 02:04 UTC, laizy commented on http/ethrpc/filters/filter_system.go
> +		hashes:    make(chan []common.Hash),
those fields should never be used, remove them to make it more clear?

2022-05-17 02:04 UTC, laizy commented on http/ethrpc/filters/filter_system.go
> +		headers:   make(chan *types.Header),
ditto

2022-05-17 02:04 UTC, laizy commented on http/ethrpc/filters/filter_system.go
> +		headers:   make(chan *types.Header),
those fields should never be used, remove them to make it more clear?

2022-05-17 02:04 UTC, laizy commented on http/ethrpc/filters/filter.go
> +	// TODO limit search span
do it.

2022-06-03 05:23 UTC, laizy requested changes

2022-06-03 05:23 UTC, laizy commented on core/store/indexstore/bloombits.go
> +func (this *bloomIndexer) SetValidSections(sections uint32) error {
why need save this? the section after the start index height will always be available.

2022-06-03 05:23 UTC, laizy commented on core/store/indexstore/indexer.go
> +	db, err := leveldbstore.NewLevelDBStore(filepath.Join(dataDir, bloomIdxDir))
no need new db.

2022-06-03 05:23 UTC, laizy commented on core/store/indexstore/indexer.go
> +		err = backend.PutFilterStart(curBlockHeight)
I do not think we need save all the zero bytes in db before the height evm feature enabled.

2022-06-03 05:23 UTC, laizy commented on core/store/indexstore/indexer.go
> +			i.backend.Process(hash, number, bloom, i.start)
why not call this when persist each block so the bloom cache code can be cleaned.

2022-06-03 05:23 UTC, laizy commented on core/store/ledgerstore/ledger_store.go
> +	this.setBloomCache(blockHeight, bloom)
update the bloom bits directly, and persist to blockStore if reached 4096.

2022-06-08 02:50 UTC, hero5512 commented on core/store/indexstore/bloombits.go
> +func (this *bloomIndexer) SetValidSections(sections uint32) error {
done

2022-11-02 09:01 UTC, merged