Head line: add cli implement first version.
ontio/ontology pull request #15
Opened 2018-04-16 03:48 UTC by Yihen

add cmd package for cli module.
  restruct main.go file.

  Signed-off-by:liuyihen@onchain.com

2018-04-16 06:12 UTC, laizy requested changes

2018-04-16 06:12 UTC, laizy commented on account/client.go
> +	if client == nil {
meaningless condition check , return client directly.

2018-04-16 06:12 UTC, laizy commented on cmd/info_cmd.go
> +	ledger.DefLedger, _ = ledger.NewLedger()
info should query from restful api , can not get from db directly

2018-04-16 06:15 UTC, laizy commented on cmd/info_cmd.go
> +	ledger.DefLedger, _ = ledger.NewLedger()
because command is executed in a separate process

2018-04-16 06:20 UTC, Yihen-Liu commented on cmd/info_cmd.go
> +	ledger.DefLedger, _ = ledger.NewLedger()
Thx.

2018-04-16 09:16 UTC, laizy requested changes

2018-04-16 09:16 UTC, laizy commented on cmd/utils/flags.go
> +		Usage: "Rinkeby network: pre-configured proof-of-authority test network",
what's this?

2018-04-17 10:58 UTC, Yihen commented
New version has been given pull request.
Close this one.

2018-04-17 10:58 UTC, closed without merging