vbft governance support
ontio/ontology pull request #150
Opened 2018-05-14 09:36 UTC by Honglei-Cong

1. governance contract support
2. fee splitting for deposited tokens
3. vbft chain support for governance
4. vbft bug fixings

2018-05-14 10:15 UTC, laizy requested changes

2018-05-14 10:15 UTC, laizy commented on consensus/vbft/block_pool.go
> +		block.Block.Transactions = systemTxs
when dealing with `block, transaction` etc, we implicitly assume they are immutable after construction. here you have modified block's transactions, so you need explicitly recalculate transaction root and set block.Hash to nil.

2018-05-15 06:33 UTC, Honglei-Cong commented
Some important fix needed for the pull request.
close it now.

2018-05-15 06:33 UTC, closed without merging

2018-05-15 06:34 UTC, laizy commented on consensus/vbft/msg_pool.go
> +	if _, present := self.msgHashs[msgHash]; present {
need adjust the return value to `bool`