ONT-566 add admin role;fix commitDpos bug;update blacknode logic
ontio/ontology pull request #192
Opened 2018-05-21 06:19 UTC by siovanus

2018-05-28 03:30 UTC, Honglei-Cong requested changes

2018-05-28 03:30 UTC, Honglei-Cong commented on smartcontract/service/native/governance/param.go
> +	"io"
format import

2018-05-28 03:30 UTC, Honglei-Cong commented on smartcontract/service/native/governance/utils.go
> +	binary.LittleEndian.PutUint32(p[:], view)
please use serialization interface.  

same comments for the following GetBytesUint32.

2018-05-28 03:30 UTC, Honglei-Cong commented on smartcontract/service/native/governance/utils.go
> +	"encoding/binary"
don't use binary, please change to serialization.

2018-05-28 03:30 UTC, Honglei-Cong commented on smartcontract/service/native/governance/param.go
> +	this.PeerPubkey = peerPubkey
update this.[*] after all data members are deserialized successfully.

2018-05-28 03:30 UTC, Honglei-Cong commented on smartcontract/service/native/governance/param.go
> +	if err := serialization.WriteVarUint(w, uint64(len(this.PeerPubkeyList))); err != nil {
serialization.WriteUint32 ? 
or serialization.WriteUint64 ?

2018-05-28 03:30 UTC, Honglei-Cong commented on smartcontract/service/native/governance/param.go
> +	if err := serialization.WriteVarUint(w, uint64(len(this.PosList))); err != nil {
WriteUint64 ?

2018-05-28 03:33 UTC, Honglei-Cong requested changes

2018-05-28 03:33 UTC, Honglei-Cong commented on smartcontract/service/native/governance/param.go
> +		this.PeerPubkeyList = append(this.PeerPubkeyList, k)
make an empty array firstly,
then append to the empty array.

2018-05-28 03:33 UTC, Honglei-Cong commented on smartcontract/service/native/governance/param.go
> +		this.PosList = append(this.PosList, k)
same comment as the above one.

2018-05-28 03:44 UTC, Honglei-Cong requested changes

2018-05-28 03:44 UTC, Honglei-Cong commented on smartcontract/service/native/governance/param.go
> +	m, err := serialization.ReadVarUint(r, 0)
check m == n ?

2018-05-28 03:44 UTC, Honglei-Cong commented on smartcontract/service/native/governance/param.go
> +	if err := serialization.WriteVarUint(w, uint64(len(this.WithdrawList))); err != nil {
similar comment as VoteForPeer

2018-05-28 03:44 UTC, Honglei-Cong commented on smartcontract/service/native/governance/param.go
> +	this.N = n
same comment as above, 
update this after all data members deserialized successfully.

2018-05-30 08:42 UTC, laizy commented on smartcontract/service/native/governance/governance.go
> +	//init globalParam
all the config value got from external environment should be serialized in argument.

2018-05-30 11:01 UTC, laizy requested changes

2018-05-30 11:01 UTC, laizy commented on smartcontract/service/native/init/init.go
> +		fmt.Println("vbft config serialize failed")
use log

2018-05-30 11:01 UTC, laizy commented on smartcontract/service/native/governance/governance.go
> +	fmt.Println("############################")
remove this

2018-05-31 04:22 UTC, laizy approved these changes

2018-05-31 04:22 UTC, merged