ONT-707 optimize vbft make proposal
ontio/ontology pull request #255
Opened 2018-06-04 02:34 UTC by xiemylogos

2018-06-04 05:32 UTC, Honglei-Cong requested changes

2018-06-04 05:32 UTC, Honglei-Cong commented on consensus/vbft/service.go
> +		log.Errorf("BlockPrposalMessage check blocknum:%d,prevhash:%d,msg prevhash:", msg.GetBlockNum(), prevBlkHash, msgPrevBlkHash)
print hash with hex.encode

2018-06-04 05:32 UTC, Honglei-Cong commented on core/store/ledgerstore/ledger_store.go
go import fmt

2018-06-04 05:32 UTC, Honglei-Cong commented on core/store/ledgerstore/ledger_store.go
move 'consensusType := strings.ToLower(config.DefConfig.Genesis.ConsensusType)'  here.

2018-06-04 08:01 UTC, Honglei-Cong submitted a review, later dismissed

2018-06-05 05:59 UTC, laizy requested changes

2018-06-05 05:59 UTC, laizy commented on consensus/vbft/service.go
> +	if bytes.Compare(prevBlkHash.ToArray(), msgPrevBlkHash.ToArray()) != 0 {
you can use `prevBlkHash != msgPrevBlkHash` directly

2018-06-05 11:21 UTC, Honglei-Cong commented on consensus/vbft/service.go
> +	if self.checkNeedUpdateChainConfig(blkNum) || self.checkUpdateChainConfig() {
do this check before metaLock.Lock() ?

2018-06-05 11:21 UTC, Honglei-Cong commented on consensus/vbft/service.go
> +	if self.checkNeedUpdateChainConfig(blkNum) || self.checkUpdateChainConfig() {
btw, 
always self.config = block.Info.NewChainConfig when block.Info.NewChainConfig is not nil ?

2018-06-06 01:40 UTC, Honglei-Cong approved these changes

2018-06-06 05:10 UTC, merged