update native contract adapt to neovm
ontio/ontology pull request #281
Opened 2018-06-09 03:45 UTC by tanZiWen

2018-06-09 11:48 UTC, laizy requested changes

2018-06-09 11:48 UTC, laizy commented on vm/neovm/func_array.go
> +		item.Add(item)
seems interesting. add item to it self?

2018-06-10 03:20 UTC, tanZiWen commented on vm/neovm/func_array.go
> +		item.Add(item)
fix

2018-06-10 03:20 UTC, Arbio5zt requested changes

2018-06-10 03:20 UTC, Arbio5zt commented on core/store/ledgerstore/ledger_store.go
> +	engine, _ := sc.NewExecuteEngine(invoke.Code)
miss error catch.

2018-06-10 03:20 UTC, Arbio5zt commented on core/store/ledgerstore/tx_handler.go
> +	fmt.Println("isCharge:", isCharge)
need to change fmt print to debug print.

2018-06-10 03:20 UTC, Arbio5zt commented on core/store/ledgerstore/tx_handler.go
> +	engine, _ := sc.NewExecuteEngine(invoke.Code)
miss error catch.

2018-06-10 03:20 UTC, Arbio5zt commented on core/store/ledgerstore/tx_handler.go
> +	service, _ := sc.NewNativeService()
miss error catch.

2018-06-10 03:45 UTC, luodanwg commented on vm/neovm/types/array.go
> +	return true
the GetBoolean name means get the bool value, but can only return true ?

2018-06-10 05:44 UTC, Arbio5zt approved these changes

2018-06-10 05:58 UTC, merged