[ONT-791] Cli add gen multi signature address cmd
ontio/ontology pull request #289
Opened 2018-06-09 10:22 UTC by gasby88

signed-off-by:wangbing@onchain.com

2018-06-09 14:31 UTC, Arbio5zt requested changes

2018-06-09 14:31 UTC, luodanwg commented on cmd/account_cmd.go
> +	pkSize := len(pks)
move line 599~ 605 here to check the value first before make.

2018-06-09 15:31 UTC, laizy commented
pending this for one or two days after intergration branch is ready. Since it has some changes in that branch.

2018-06-13 06:51 UTC, laizy requested changes

2018-06-13 06:51 UTC, laizy commented on cmd/account.go
> +const MAX_PUBLIC_KEY_SIZE = 24
neo's max size is 1024, and defined in common/constants module.

2018-06-13 06:51 UTC, laizy commented on cmd/utils/flags.go
> +		Usage: "M of multi signature address. m must > 0 and < 24, and m must <= number of pub key",
update to `1024`

2018-06-13 06:51 UTC, laizy commented on cmd/utils/flags.go
> +		Usage: "Pub key list of multi address, split pub key with `,`. Number of pub key must > 0 and <= 24",
ditto

2018-06-15 06:29 UTC, laizy approved these changes

2018-06-15 06:29 UTC, merged