add native notify docs
ontio/ontology pull request #715
Opened 2018-12-18 11:28 UTC by siovanus

2018-12-19 04:02 UTC, tanZiWen commented
add english version support

2018-12-25 02:33 UTC, Honglei-Cong requested changes
why Chinese version?

2019-01-09 16:05 UTC, Honglei-Cong requested changes

2019-01-09 16:05 UTC, Honglei-Cong commented on docs/specifications/native_contract/authnotify.md
> +Notify格式
"格式"?

2019-01-09 16:05 UTC, Honglei-Cong commented on docs/specifications/native_contract/authnotify.md
> +Assign auth of function to role
"auth" = authentication?

2019-01-09 16:05 UTC, Honglei-Cong commented on docs/specifications/native_contract/authnotify.md
> +Assign auth of function to role
Please fix all abbr. first.

2019-01-10 09:47 UTC, jonatanblockchain commented on docs/specifications/native_contract/authnotify.md
> +Notify格式
> "格式"?

Same here:

https://github.com/ontio/ontology/blob/f62d296593189879d80941ff28d5d7cae0b31198/docs/specifications/native_contract/ontnotify.md

2019-04-01 10:04 UTC, laizy approved these changes

2019-04-01 10:08 UTC, merged