add map .keys .values .has_key list.remove, DCALL support
ontio/ontology pull request #716
Opened 2018-12-19 06:17 UTC by carltraveler

a. add map.keys()
b. add map.has_key()
c. add map.values()
d. add list.remove(element)
e. add DCALL get the jump target from top stack

2018-12-20 06:16 UTC, Honglei-Cong commented
For VM opcode changes, please make proposal on OEP firstly.

2018-12-21 08:10 UTC, laizy commented on vm/neovm/func_array.go
> +			if index.Equals(obj) {
seems really strange here.

2018-12-21 08:13 UTC, laizy commented on vm/neovm/func_array.go
> +		for k := range mapitem {
avoid duplicated code.

2018-12-21 08:22 UTC, laizy commented on vm/neovm/func_flowcontrol.go
> +	if offset < 0 || int(offset) > len(e.Context.Code) {
is `>=`

2018-12-21 08:24 UTC, laizy commented on vm/neovm/func_flowcontrol.go
> +		return FAULT, errors.ERR_DCALL_OFFSET_ERROR
`offset` is confusing. it is an absolute position.

2018-12-21 08:27 UTC, laizy commented on vm/neovm/func_validate.go
> +		barr, err := item.GetByteArray()
use `barr, _ :=` or  check error

2018-12-21 08:33 UTC, laizy commented on vm/neovm/func_validate.go
> +	if offset < 0 || int(offset) > len(e.Context.Code) {
`>=`

2018-12-24 03:16 UTC, carltraveler commented on vm/neovm/func_array.go
> +		for k := range mapitem {
ok, I will realize it with a function

2018-12-24 03:16 UTC, carltraveler commented on vm/neovm/func_flowcontrol.go
> +	if offset < 0 || int(offset) > len(e.Context.Code) {
thanks. it is

2018-12-24 03:16 UTC, carltraveler commented on vm/neovm/func_flowcontrol.go
> +		return FAULT, errors.ERR_DCALL_OFFSET_ERROR
change it to target

2018-12-24 03:17 UTC, carltraveler commented on vm/neovm/func_validate.go
> +	if offset < 0 || int(offset) > len(e.Context.Code) {
same obove

2018-12-24 03:25 UTC, carltraveler commented on vm/neovm/func_flowcontrol.go
> +	if offset < 0 || int(offset) > len(e.Context.Code) {
oh, if offset = len(e.Context.code) will out of bound

2019-01-04 04:05 UTC, laizy requested changes

2019-01-04 04:05 UTC, laizy commented on vm/neovm/func_validate.go
> +			return errors.ERR_REMOVE_NOT_SUPPORT
this is not needed. has guaranteed to be `*types.Map`.

2019-01-04 04:05 UTC, laizy commented on vm/neovm/func_validate.go
> +		if _, ok := item.(*types.Array); !ok {
ditto

2019-02-18 12:13 UTC, tanZiWen submitted a review, later dismissed

2019-02-20 10:14 UTC, laizy commented
add unit test?

2019-03-20 03:47 UTC, laizy commented
missing `dcall` opcode test.

2019-03-21 02:56 UTC, laizy approved these changes

2019-03-21 02:56 UTC, merged