update dapp fee split
ontio/ontology pull request #727
Opened 2019-01-14 03:40 UTC by siovanus

gas fee 50% to node, 50% to a multisign address
if multisign address is not set, all gas fee goes to node
50% is configurable

2019-01-21 07:28 UTC, laizy commented on smartcontract/service/native/governance/param.go
> +	if err := serialization.WriteVarBytes(w, this.Address[:]); err != nil {
use `utils.WriteAddress` to consistent with `Deserialize` function

2019-01-21 07:28 UTC, laizy commented on smartcontract/service/native/governance/method.go
> +	balance1 := balance * uint64(100-globalParam2.DappFee) / 100
seems incompatible with old version. if `DappFee == 0`, old version `income = balance - splitFee`, new version: `income = 0 - splitFee`

2019-01-21 07:28 UTC, laizy commented on smartcontract/service/native/governance/method.go
> +	income := balance2 - splitFee
can guarantee not underflow?

2019-03-04 11:38 UTC, Honglei-Cong requested changes

2019-03-04 11:38 UTC, Honglei-Cong commented on smartcontract/service/native/governance/governance.go
> +	adminAddress, err := global_params.GetStorageRole(native,
operatorAddress?

2019-03-04 11:38 UTC, Honglei-Cong commented on smartcontract/service/native/governance/method.go
> +		}
add dappIncome to splitSum ?

2019-03-21 08:08 UTC, laizy approved these changes

2019-03-21 08:08 UTC, merged