Fix: transfer asset does't successfully but for using default account
ontio/ontology pull request #73
Opened 2018-04-25 12:34 UTC by Yihen

Signed-off-by: liuyihen@onchain.com

2018-04-25 13:48 UTC, laizy requested changes

2018-04-25 13:48 UTC, laizy commented on cmd/asset_cmd.go
>  	acct := account.Open(account.WALLET_FILENAME, passwd)
need check `acct == nil` to avoid panic

2018-04-26 03:24 UTC, laizy requested changes

2018-04-26 03:24 UTC, laizy commented on cmd/asset_cmd.go
> +		fmt.Println("Parase address from base58 error")
`:s/Parase/Parse`

2018-04-26 03:33 UTC, Yihen commented on cmd/asset_cmd.go
> +		fmt.Println("Parase address from base58 error")
what a shame. Have modified.

2018-04-26 06:36 UTC, Arbio5zt approved these changes
approve

2018-04-26 06:36 UTC, merged