fix vbft shard user stake and seal block bug
ontio/ontology pull request #826
Opened 2019-03-27 09:58 UTC by qiluge

1. fix stake param shard id serialize bug;
2. update vbft parent height at each proposal;
3. only update user unbound ong info while stake asset is ONT contract

2019-03-27 10:34 UTC, laizy requested changes

2019-03-27 10:34 UTC, laizy commented on smartcontract/service/native/shard_stake/params.go
> +	ShardId uint64
why modify this?

2019-03-27 10:34 UTC, laizy commented on smartcontract/service/native/shard_stake/params.go
> +	this.ShardId = id
not all uint64 are valid ShardID, the original check is needed.

2019-03-27 10:38 UTC, laizy commented on smartcontract/service/native/shard_stake/params.go
> +	ShardId    uint64
revert all those changes back

2019-03-28 06:09 UTC, qiluge commented
@laizy fixed shard serialize problem

2019-03-28 08:06 UTC, Honglei-Cong approved these changes

2019-03-28 08:06 UTC, merged