add unit test case of account and common
ontio/ontology pull request #90
Opened 2018-04-28 08:21 UTC by qiluge

the compact_uint_test test error, because of  the index out of range. See the $GOROOT/src/encoding/binary/binary.go, line 76 (bounds check hint to compiler; see golang.org/issue/14808).

2018-04-28 08:43 UTC, laizy requested changes

2018-04-28 08:43 UTC, laizy commented on account/account_test.go
> +	assert.Equal(t, accounts[0].Address, types.AddressFromPubKey(accounts[0].PublicKey))
you can add `""` in names to avoid handle  this special case .

2018-04-28 08:43 UTC, laizy commented on account/file_store_test.go
> +	assert.Equal(t, deaultAccount, accout)
delete the `wallet.dat` file before function return

2018-04-28 08:43 UTC, laizy commented on common/common_test.go
> +	fmt.Println(stringAfterTrans)
do not print in test file

2018-04-28 08:43 UTC, laizy commented on common/common_test.go
> +	fmt.Println(nonce1)
and here

2018-05-02 01:57 UTC, qiluge commented
Thanks，have modified。

2018-05-02 02:37 UTC, laizy approved these changes

2018-05-02 02:37 UTC, merged