add limit of array append
ontio/ontology pull request #931
Opened 2019-05-30 06:58 UTC by tanZiWen

2019-05-30 07:48 UTC, laizy commented on vm/neovm/func_validate.go
> +func checkStackSize(s types.StackItems, length *int) bool {
what are you doing here?

2019-05-30 07:56 UTC, laizy commented on vm/neovm/params.go
> +	MAX_ARRAY_SIZE            int    = 1024
remove `int`, `uint32`,  constant number do not need type info

2019-05-30 07:57 UTC, laizy commented on vm/neovm/func_stack_test.go
> +	for i := 0; i < 1024; i++ {
from your implementation. i think `1` is enough to lead the following assert to false.

2019-05-30 08:44 UTC, tanZiWen commented on vm/neovm/func_validate.go
> +func checkStackSize(s types.StackItems, length *int) bool {
add stack deep check

2019-06-01 08:02 UTC, WyattMufson requested changes

2019-06-01 08:02 UTC, WyattMufson commented on vm/neovm/func_array.go
> +			return FAULT, fmt.Errorf("%s", "[opRemove] index not a interger!")
Should fix the spelling of "integer"

2019-06-01 08:02 UTC, WyattMufson commented on vm/neovm/func_array.go
> +			return FAULT, fmt.Errorf("%s", "[opRemove]get Array error!")
Should add a space after the "]"

2019-06-01 08:03 UTC, WyattMufson commented
This will resolve #930

2019-06-03 05:32 UTC, laizy commented
ping @tanZiWen

2019-06-03 11:17 UTC, tanZiWen commented on vm/neovm/func_array.go
> +			return FAULT, fmt.Errorf("%s", "[opRemove] index not a interger!")
yes, it's error spell

2019-06-03 11:18 UTC, tanZiWen commented on vm/neovm/func_array.go
> +			return FAULT, fmt.Errorf("%s", "[opRemove]get Array error!")
updated

2019-06-03 11:34 UTC, WyattMufson submitted a review, later dismissed

2019-06-03 11:34 UTC, WyattMufson commented on vm/neovm/func_array.go
> +			return FAULT, fmt.Errorf("%s", "[opRemove] index not a interger!")
Great!

2019-06-03 11:34 UTC, WyattMufson commented on vm/neovm/func_array.go
> +			return FAULT, fmt.Errorf("%s", "[opRemove]get Array error!")
Awesome

2019-06-12 09:08 UTC, laizy commented on vm/neovm/func_stack_test.go
> +	assert.False(t, CheckStackSize([]types.StackItems{s, s, s}))
check 1023 is ok.

2019-06-12 09:08 UTC, laizy commented on vm/neovm/func_validate.go
> +func CheckStackSize(items []types.StackItems) bool {
remove this

2019-06-12 09:12 UTC, tanZiWen commented on vm/neovm/func_validate.go
> +func CheckStackSize(items []types.StackItems) bool {
done

2019-06-19 08:37 UTC, laizy commented
fixed in #958

2019-06-19 08:37 UTC, closed without merging