cli-cmd/account: add new files and change some related packages.
ontio/ontology pull request #97
Opened 2018-05-03 06:24 UTC by Doresimon

# modify some functions to unique package.

1. func: password enter
2. func: add account
3. func: set account
4. func: delete account
5. func: encrypt account file

# refactor types from account.go to account_cmd.go

# add -label flag for <account add> <account set>
* <account list> will show label info at the same time
* default label for an account is ""(blank string)

# add <account import> sub command
* account import -source xxx: to import accounts in xxx to current wallet file.
* use -file <filename> to specify current wallet file. default name is "wallet.dat". 

# change some print info.

Signed-off-by: Halo Guan <guanjixing@onchain.com>

2018-05-03 09:24 UTC, laizy requested changes

2018-05-03 09:24 UTC, laizy commented on cmd/account_cmd.go
> +	pass, _ := password.GetConfirmedPassword()
handle all err in this file.

2018-05-03 09:24 UTC, laizy commented on account/account.go
> +}
so why move all those maps here? account module does not care any of those stuff. they are just used to map user's  command line input.  so keep it untouched should be a better choice.

2018-05-06 14:55 UTC, almoslim4 approved these changes

2018-05-06 14:56 UTC, almoslim4 approved these changes

2018-05-06 14:56 UTC, almoslim4 approved these changes

2018-05-06 14:57 UTC, almoslim4 approved these changes

2018-05-07 03:47 UTC, closed without merging